### ISSUE TITLE
Upgrade Discord Bot

### ISSUE THREAD

**Issue by Thrax989** [dpwhittaker/swg-discord-bot#2]
With the Latest SWGEmu updates, The discord bot seems to go offline within a few minutes, any updates? I've used the bot for a few years, after updating to the latest code it seems to bug out after just a few minutes, any help to resolve this issue ?

**Comment by dpwhittaker** [comment]
I'm not doing much with SWG right now.  Does it log a stack trace when it bugs out?

**Comment by Thrax989** [comment]
I have not attempted to do that, can you show me how I can provide any errors, also if you need compensation for your time to fix it no problem    On Monday, November 18, 2019, 05:55:23 PM PST, David <notifications@github.com> wrote:  
 
 
I'm not doing much with SWG right now. Does it log a stack trace when it bugs out?

**Comment by Thrax989** [comment]
We were able to put a temporary fix in, but for now the issue seems to be comming from the character bot disconnecting after a few mins of being online, reconnecting the bot with a few additional lines of code in the script fixed the problem temporarily.
